com.github.johnrengelman:shadow = 8.1.1
com.palantir.gradle.plugintesting:gradle-plugin-testing-junit = 0.24.0
org.immutables:value = 2.11.6
com.google.guava:guava = 33.5.0-jre

# Test deps
com.palantir.tracing:tracing = 6.28.0
com.palantir.safe-logging:safe-logging = 3.9.0
com.palantir.tritium:tritium-registry = 0.111.0
commons-io:commons-io = 2.20.0
com.fasterxml.jackson.dataformat:jackson-dataformat-xml = 2.20.1

# conflict resolution
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.11.0
org.checkerframework:checker-qual = 3.51.1
org.junit.jupiter:* = 6.0.1
org.junit.platform:* = 6.0.1
org.junit.vintage:* = 6.0.1

# gradlePluginForTesting
org.unbroken-dome.test-sets:org.unbroken-dome.test-sets.gradle.plugin = 4.1.0
com.palantir.gradle.consistentversions:gradle-consistent-versions = 3.7.0
com.netflix.nebula:nebula-publishing-plugin = 17.2.1