com.fasterxml.jackson.*:* = 2.22.1
com.fasterxml.jackson.core:jackson-annotations = 2.22
com.gradleup.shadow:shadow-gradle-plugin = 9.3.1
org.immutables:value = 2.12.2
com.google.guava:guava = 33.6.0-jre

# Test deps
com.palantir.tracing:tracing = 6.38.0
com.palantir.safe-logging:safe-logging = 3.17.0
com.palantir.tritium:tritium-registry = 0.135.0
commons-io:commons-io = 2.22.0

# conflict resolution
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.11.0
org.checkerframework:checker-qual = 4.2.0
org.junit.jupiter:* = 6.1.2
org.junit.platform:* = 6.1.2
org.junit.vintage:* = 6.1.2

# gradlePluginForTesting
org.unbroken-dome.test-sets:org.unbroken-dome.test-sets.gradle.plugin = 4.1.0
com.palantir.gradle.consistentversions:gradle-consistent-versions = 3.16.0
com.netflix.nebula:nebula-publishing-plugin = 17.2.1
